// Routes for Login
export const HOME = '/'
export const LOGIN = '/login'
export const REGISTER = '/join'
export const FORGOT_PASSWORD = '/forgot-password'
export const DROP_DETAIL = '/drop/:drop_num'
export const PROFILE = '/profile'
export const PROFILE_EDIT = '/profile/edit'
export const PASS_DETAIL = '/pass/:pass_id'
export const PASS_BUY = '/pass-buy'
export const MARKETPLACE = '/marketplace'
export const ABOUT = '/about-us'
export const FAQ = '/faq'
export const PROFILE_PASS_DETAIL = '/profile/pass/:pass_id'